BMS mapset install:
CEDA DEFINE MAPSET(ZBANKSET) GROUP(ZBANK)
CEDA INSTALL MAPSET(ZBANKSET) GROUP(ZBANK)

ZBNK transaction install:
CEDA DEFINE TRANSACTION(ZBNK) PROGRAM(ZBANK) GROUP(ZBANK)
CEDA DEFINE PROGRAM(ZBANK) GROUP(ZBANK)
CEDA DEFINE LIBRARY(ZLOAD) GROUP(ZBANK) DSNAME01(U0210.CICS.LOADLIB)
CEDA INSTALL TRANSACTION(ZBNK) GROUP(ZBANK)
CEDA INSTALL PROGRAM(ZBANK) GROUP(ZBANK)
CEDA INSTALL LIBRARY(ZLOAD) GROUP(ZBANK)

VSAM file install:
CEMT SET FILE(VSAMZBNK) FORCECLOSE
CEDA DELETE FILE(VSAMZBNK) GROUP(ZBANK)
CEDA DEFINE FILE(VSAMZBNK) GROUP(ZBANK) DSNAME(U0210.VSAM.ZBANK) UPDATE(YES) (Without spaces in the filename 'U0210.VSAM.ZBANK', scroll with F8 trough the shown screen and check if Browse, Add, Delete are set to YES. You can set all permissions to YES to be safe.)
CEDA INSTALL FILE(VSAMZBNK) GROUP(ZBANK)
